### PR TITLE
Try out jayschema.

### PR DESCRIPTION
**Pull request by rgbkrk**
This is nbformatjs with a [JaySchema](https://github.com/natesilva/jayschema) interface.

``` JavaScript
> NotebookValidator = require('./nbformat');
[Function: NotebookValidator]
> nbv = new NotebookValidator();
{ maxRecursion: 5,
  loader: null,
  _schemaRegistry:
   { _schemas:
      { 'http://json-schema.org/draft-04/schema#': [Object],
        '/v3#': [Object],
        '/v4#': [Object] },
     _missingSchemas: {} },
  _customFormatHandlers: {},
  _refsRequested: {} }
> var fs = require('fs');
undefined
> var nbModel = JSON.parse(fs.readFileSync("tests/test4.ipynb", 'utf8'));
undefined
> nbv.validateNotebook(nbModel)
[]
> var nbModel = JSON.parse(fs.readFileSync("tests/test2.ipynb", 'utf8'));
undefined
> nbv.validateNotebook(nbModel)
[ { [Error]
    instanceContext: '#/',
    desc: 'schema not available: anon-schema:///v2#' } ]
> var nbModel = JSON.parse(fs.readFileSync("tests/invalid.ipynb", 'utf8'));
undefined
> nbv.validateNotebook(nbModel)
[ { [Error]
    instanceContext: '#/cells/0',
    resolutionScope: 'anon-schema://5421b9608f72f8ca65b7c211a732e682bdebe2ca/#/definitions/cell',
    constraintName: 'oneOf',
    constraintValue: [ [Object], [Object], [Object] ],
    desc: 'does not validate against any of these schemas; must validate against one and only one of them',
    kind: 'SubSchemaValidationError',
    subSchemaValidationErrors:
     { '#/definitions/raw_cell': [Object],
       '#/definitions/markdown_cell': [Object],
       '#/definitions/code_cell': [Object] } },
  { [Error]
    instanceContext: '#/cells/2',
    resolutionScope: 'anon-schema://5421b9608f72f8ca65b7c211a732e682bdebe2ca/#/definitions/cell',
    constraintName: 'oneOf',
    constraintValue: [ [Object], [Object], [Object] ],
    desc: 'does not validate against any of these schemas; must validate against one and only one of them',
    kind: 'SubSchemaValidationError',
    subSchemaValidationErrors:
     { '#/definitions/raw_cell': [Object],
       '#/definitions/markdown_cell': [Object],
       '#/definitions/code_cell': [Object] } },
  { [Error]
    instanceContext: '#/cells/3',
    resolutionScope: 'anon-schema://5421b9608f72f8ca65b7c211a732e682bdebe2ca/#/definitions/cell',
    constraintName: 'oneOf',
    constraintValue: [ [Object], [Object], [Object] ],
    desc: 'does not validate against any of these schemas; must validate against one and only one of them',
    kind: 'SubSchemaValidationError',
    subSchemaValidationErrors:
     { '#/definitions/raw_cell': [Object],
       '#/definitions/markdown_cell': [Object],
       '#/definitions/code_cell': [Object] } } ]
```

/cc @jdfreder

### CODE REVIEW

**Comment by rgbkrk** [comment]
I'm going to check out [`ajv`](https://github.com/epoberezkin/ajv) next.

**Comment by jdfreder** [comment]
I like the output.

**Comment by rgbkrk** [comment]
> I like the output.

Me too.

**Comment by rgbkrk** [comment]
Closing down old PRs.

I definitely need to revisit this repo sometime.

**Pull request closed without merging**
